// The cross-sectional backtest, ported from advisor/portfolio_backtest.py.
//
// It lives here because the sandbox that wrote it cannot reach an exchange,
// while Netlify can — and the ten years of daily bars this needs are already in
// the blob store that the nightly ingest fills.
//
// A port is a place where two implementations quietly drift apart, so this one
// is pinned: tests-backtest.mjs runs a deterministic panel through this code and
// asserts the numbers match a fixture generated by the Python original. If the
// two ever disagree, the test fails rather than the results silently differing.

export const COSTS = {
  sttBuy: 0.001, sttSell: 0.001,
  exchangeTxn: 0.0000297, sebi: 0.000001,
  stampDutyBuy: 0.00015, brokerage: 0.0, gst: 0.18,
  slippage: 0.0010,
};

export function oneWay(isBuy, c = COSTS) {
  const stt = isBuy ? c.sttBuy : c.sttSell;
  const gst = (c.brokerage + c.exchangeTxn) * c.gst;
  const stamp = isBuy ? c.stampDutyBuy : 0;
  return stt + c.exchangeTxn + c.sebi + stamp + c.brokerage + gst + c.slippage;
}
export const roundTrip = (c = COSTS) => oneWay(true, c) + oneWay(false, c);

const TRADING_DAYS = 250;

function weightsFor(symbols, cfg) {
  if (!symbols.length) return {};
  const raw = 1 / symbols.length;
  const capped = {};
  for (const s of symbols) capped[s] = Math.min(raw, cfg.maxWeight);
  const total = Object.values(capped).reduce((a, b) => a + b, 0);
  if (total <= 0) return {};
  const out = {};
  for (const s of symbols) out[s] = capped[s] / total;
  return out;
}

/**
 * scoresByT: { t: { symbol: score } }  — scores known AT index t
 * prices:    { symbol: [closes] }      — one aligned series per symbol
 *
 * Forward returns are computed here from the prices, never supplied, so a
 * caller cannot hand in the future by accident.
 */
export function backtest(scoresByT, prices, cfg = {}) {
  const c = { topN: 20, rebalanceEvery: 21, maxWeight: 0.10, costs: COSTS, ...cfg };
  const ts = Object.keys(scoresByT).map(Number).sort((a, b) => a - b);
  const empty = { periods: 0, netAnnual: 0, grossAnnual: 0, annualVol: 0,
                  sharpe: 0, maxDrawdown: 0, turnover: 0, costDrag: 0,
                  hitRate: 0, periodReturns: [], equity: [1], namesHeld: 0 };
  if (ts.length < 2) return empty;

  const equity = [1.0];
  const periodReturns = [], turnovers = [], names = [];
  let held = {};
  const rt = roundTrip(c.costs);

  for (let i = 0; i < ts.length - 1; i++) {
    const t = ts[i], nxt = ts[i + 1];
    const scores = scoresByT[t];
    const eligible = Object.keys(scores).filter((s) =>
      scores[s] != null && prices[s] && prices[s].length > nxt &&
      prices[s][t] && prices[s][nxt]);
    const picks = eligible.sort((a, b) => scores[b] - scores[a]).slice(0, c.topN);
    const w = weightsFor(picks, c);
    names.push(picks.length);

    let gross = 0;
    for (const s of picks) gross += w[s] * (prices[s][nxt] / prices[s][t] - 1);

    const all = new Set([...Object.keys(w), ...Object.keys(held)]);
    let turnover = 0;
    for (const s of all) turnover += Math.abs((w[s] || 0) - (held[s] || 0));
    turnover /= 2;
    turnovers.push(turnover);

    const net = gross - turnover * rt;
    periodReturns.push(net);
    equity.push(equity[equity.length - 1] * (1 + net));
    held = w;
  }

  const n = periodReturns.length;
  if (!n) return empty;
  const perYear = TRADING_DAYS / c.rebalanceEvery;
  const mean = periodReturns.reduce((a, b) => a + b, 0) / n;
  const varr = n > 1
    ? periodReturns.reduce((a, x) => a + (x - mean) ** 2, 0) / (n - 1) : 0;
  const sd = Math.sqrt(varr);
  const annVol = sd * Math.sqrt(perYear);
  const last = equity[equity.length - 1];
  const annNet = last > 0 ? Math.pow(last, perYear / n) - 1 : -1;
  const avgTurn = turnovers.reduce((a, b) => a + b, 0) / turnovers.length;
  const costDrag = avgTurn * rt * perYear;

  let peak = equity[0], mdd = 0;
  for (const e of equity) { peak = Math.max(peak, e); mdd = Math.min(mdd, e / peak - 1); }

  return {
    periods: n,
    netAnnual: annNet,
    grossAnnual: annNet + costDrag,
    annualVol: annVol,
    sharpe: annVol > 0 ? annNet / annVol : 0,
    maxDrawdown: mdd,
    turnover: avgTurn,
    costDrag,
    hitRate: periodReturns.filter((r) => r > 0).length / n,
    periodReturns, equity,
    namesHeld: names.reduce((a, b) => a + b, 0) / names.length,
  };
}

/* A small deterministic generator, so a shuffle run is reproducible and a
   result can be re-derived rather than merely believed. */
function mulberry32(seed) {
  let a = seed >>> 0;
  return function () {
    a |= 0; a = (a + 0x6D2B79F5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/**
 * Permute the scores across symbols and see whether the result survives.
 * Everything else is identical — universe, dates, costs, turnover — so only
 * the mapping from score to symbol is destroyed.
 */
export function shuffleTest(scoresByT, prices, cfg = {}, runs = 24, seed = 17,
                            alpha = 0.05) {
  const real = backtest(scoresByT, prices, cfg);
  const rnd = mulberry32(seed);
  const shuffled = [];
  for (let r = 0; r < runs; r++) {
    const permuted = {};
    for (const t of Object.keys(scoresByT)) {
      const syms = Object.keys(scoresByT[t]);
      const vals = syms.map((s) => scoresByT[t][s]);
      for (let i = vals.length - 1; i > 0; i--) {
        const j = Math.floor(rnd() * (i + 1));
        [vals[i], vals[j]] = [vals[j], vals[i]];
      }
      permuted[t] = Object.fromEntries(syms.map((s, i) => [s, vals[i]]));
    }
    shuffled.push(backtest(permuted, prices, cfg).sharpe);
  }
  shuffled.sort((a, b) => a - b);
  const better = shuffled.filter((s) => s >= real.sharpe).length;
  const p = (better + 1) / (runs + 1);
  const minP = 1 / (runs + 1);
  const enough = minP <= alpha;
  const median = shuffled[Math.floor(shuffled.length / 2)];

  return {
    realSharpe: real.sharpe,
    shuffledMedian: median,
    shuffledBest: shuffled[shuffled.length - 1],
    // The only number here that means skill. Raw Sharpe in a long-only book is
    // mostly market exposure: a random basket in a rising market looks fine.
    skillAboveChance: real.sharpe - median,
    pValue: p,
    minAchievableP: minP,
    runsSufficient: enough,
    passes: Boolean(enough && p <= alpha),
    reading: !enough
      ? `only ${runs} permutations, so no p-value below ${minP.toFixed(3)} is reachable`
      : (enough && p <= alpha)
        ? "the ranking is doing the work — shuffling it destroys the result"
        : "shuffling the scores produces a comparable result, so the edge is not "
          + "coming from the ranking",
  };
}

export function walkForward(scoresByT, prices, folds = 4, cfg = {}) {
  const ts = Object.keys(scoresByT).map(Number).sort((a, b) => a - b);
  if (ts.length < folds * 4) {
    return { ok: false, why: `need at least ${folds * 4} rebalances for ${folds} folds` };
  }
  const size = Math.floor(ts.length / folds);
  const out = [];
  for (let i = 0; i < folds; i++) {
    const chunk = i < folds - 1 ? ts.slice(i * size, (i + 1) * size) : ts.slice(i * size);
    const sub = {};
    for (const t of chunk) sub[t] = scoresByT[t];
    const r = backtest(sub, prices, cfg);
    out.push({ fold: i + 1, periods: r.periods, netAnnual: r.netAnnual,
               sharpe: r.sharpe, maxDrawdown: r.maxDrawdown });
  }
  const positive = out.filter((f) => f.sharpe > 0).length;
  return {
    ok: true, folds: out, positiveFolds: positive, consistency: positive / folds,
    reading: positive === folds ? "consistent across every slice of history"
      : positive >= folds / 2
        ? `worked in ${positive} of ${folds} periods — carried by some regimes`
        : "failed in most periods; the full-sample result is not evidence",
  };
}

/* ---------------- the signals being tested ---------------- */
// Deliberately few and well documented. Each variant tried is counted, because
// the tenth thing you try is not the same evidence as the first.
export const SIGNALS = {
  momentum_12_1: {
    label: "12-month momentum, skipping the last month",
    note: "the most replicated cross-sectional anomaly there is; the skip avoids "
        + "the short-term reversal that contaminates a raw 12-month measure",
    score: (closes, t) => (t < 252 ? null
      : closes[t - 21] / closes[t - 252] - 1),
  },
  momentum_6_1: {
    label: "6-month momentum, skipping the last month",
    note: "a shorter formation window, included to see whether the result is an "
        + "artefact of one particular lookback",
    score: (closes, t) => (t < 147 ? null : closes[t - 21] / closes[t - 126] - 1),
  },
  low_volatility: {
    label: "low volatility",
    note: "the low-risk anomaly; included because it is nearly uncorrelated with "
        + "momentum, which is what the combination mathematics actually needs",
    score: (closes, t) => {
      if (t < 120) return null;
      let s = 0, n = 0;
      for (let i = t - 120; i < t; i++) {
        if (closes[i] > 0 && closes[i + 1] > 0) {
          const r = Math.log(closes[i + 1] / closes[i]); s += r * r; n++;
        }
      }
      return n > 30 ? -Math.sqrt(s / n) : null;     // negated: less vol ranks higher
    },
  },
};

export function buildScores(prices, signalKey, rebalanceEvery = 21, warmup = 260) {
  const sig = SIGNALS[signalKey];
  if (!sig) throw new Error(`unknown signal ${signalKey}`);
  const lengths = Object.values(prices).map((p) => p.length);
  const n = lengths.length ? Math.min(...lengths) : 0;
  const scores = {};
  for (let t = warmup; t < n - rebalanceEvery; t += rebalanceEvery) {
    const row = {};
    for (const [sym, closes] of Object.entries(prices)) {
      const v = sig.score(closes, t);
      if (v != null && Number.isFinite(v)) row[sym] = v;
    }
    if (Object.keys(row).length >= 10) scores[t] = row;
  }
  return scores;
}

/* ---------------- paying for the search ---------------- */
const EULER = 0.5772156649015329;

function invNorm(p) {
  const a=[-39.69683028665376,220.9460984245205,-275.9285104469687,
           138.3577518672690,-30.66479806614716,2.506628277459239];
  const b=[-54.47609879822406,161.5858368580409,-155.6989798598866,
           66.80131188771972,-13.28068155288572];
  const c=[-0.007784894002430293,-0.3223964580411365,-2.400758277161838,
           -2.549732539343734,4.374664141464968,2.938163982698783];
  const d=[0.007784695709041462,0.3224671290700398,2.445134137142996,
           3.754408661907416];
  const pl = 0.02425;
  let q, r;
  if (p < pl) { q = Math.sqrt(-2*Math.log(p));
    return (((((c[0]*q+c[1])*q+c[2])*q+c[3])*q+c[4])*q+c[5]) /
           ((((d[0]*q+d[1])*q+d[2])*q+d[3])*q+1); }
  if (p > 1-pl) { q = Math.sqrt(-2*Math.log(1-p));
    return -(((((c[0]*q+c[1])*q+c[2])*q+c[3])*q+c[4])*q+c[5]) /
            ((((d[0]*q+d[1])*q+d[2])*q+d[3])*q+1); }
  q = p-0.5; r = q*q;
  return (((((a[0]*r+a[1])*r+a[2])*r+a[3])*r+a[4])*r+a[5])*q /
         (((((b[0]*r+b[1])*r+b[2])*r+b[3])*r+b[4])*r+1);
}
const normCdf = (x) => {
  const s = x < 0 ? -1 : 1, z = Math.abs(x) / Math.SQRT2;
  const t = 1 / (1 + 0.3275911 * z);
  const y = 1 - (((((1.061405429*t - 1.453152027)*t) + 1.421413741)*t
          - 0.284496736)*t + 0.254829592)*t*Math.exp(-z*z);
  return 0.5 * (1 + s * y);
};

/** The best Sharpe you would expect from `trials` worthless strategies. */
export function expectedMaxSharpe(trials, variance = 1) {
  if (trials < 2) return 0;
  return Math.sqrt(variance) *
    ((1 - EULER) * invNorm(1 - 1 / trials) + EULER * invNorm(1 - 1 / (trials * Math.E)));
}

/**
 * Deflated Sharpe: is this real once you admit how many variants were tried?
 * Takes the per-period Sharpe as the backtest reports it, and the number of
 * observations behind it.
 */
export function deflatedSharpe(perPeriodSharpe, nObs, trials, periodsPerYear) {
  if (nObs < 2) return { deflated: null, why: "not enough observations" };
  const sr = perPeriodSharpe / Math.sqrt(periodsPerYear);
  const variance = (1 + (sr ** 2) / 2) / Math.max(1, nObs);
  const benchmark = expectedMaxSharpe(trials, variance);
  const z = (sr - benchmark) * Math.sqrt(nObs - 1);
  const p = normCdf(z);
  return {
    deflated: p,
    benchmarkAnnualFromLuck: benchmark * Math.sqrt(periodsPerYear),
    trialsPaidFor: trials,
    passes: p >= 0.95,
    reading: p >= 0.95
      ? "survives the multiple-testing correction"
      : "does not clear the bar once the search is paid for",
  };
}
